listen:
  stdio: true
  http: "127.0.0.1:8080"

backends:
- name: example
  transport: http
  url: "http://127.0.0.1:8000/mcp"
- name: backend2
  transport: http
  url: "http://127.0.0.1:8001/mcp"

overrides:
  example_tool: example

resource_overrides:
  "file:///example/data.txt": example

prompt_overrides:
  example_prompt: example
